name: Deploy
on: [push]

jobs:
  deploy-iam-entities:
    name: Deploy IAM Entities to AWS Account
    runs-on: ubuntu-latest
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ap-southeast-2

    # Only deploy on the master branch
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: ./scripts/setBranch.sh
      - run: ./scripts/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
